-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_external_id`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_external_id
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_external_id` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ExternalId ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `external_id` varchar(64) COMMENT 'Unique trusted external ID (generally from a legacy app/datasource). Particularly useful for deduping operations.',
  `external_id_type_id` int unsigned COMMENT 'Which External ID type does this External ID belong to.',
  PRIMARY KEY (`id`),
  INDEX `UI_external_id_type_id`(external_id_type_id),
  INDEX `index_contact_id_external_id`(contact_id, external_id),
  CONSTRAINT FK_civicrm_external_id_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
